import datetime
import json
import random

dateFormat = "%Y-%m-%d"

startDate = datetime.date(2017, 5, 1)
endDate = datetime.date(2017, 8, 31)

numberOfParticipants = 16

delta = datetime.timedelta(days=1)

data = {}
data['dbName'] = 'autogeneratedData'
data['participants'] = []

trendSleep = []
trendProd = []

trendDeltaSleep = []
trendDeltaProd = []

trendDelta2Sleep = []
trendDelta2Prod = []

deviationSleep = []
deviationProd = []

for participantIx in range(numberOfParticipants):
    trendSleep.append(random.uniform(4,12))
    trendProd.append(random.uniform(0,10))

    trendDeltaSleep.append(random.uniform(-0.01,0.01))
    trendDeltaProd.append(random.uniform(-0.01,0.01))

    trendDelta2Sleep.append(random.uniform(-0.001,0.001))
    trendDelta2Prod.append(random.uniform(-0.001,0.001))

    deviationSleep.append(random.uniform(.25,2))
    deviationProd.append(random.uniform(.5,4))

for participantIx in range(numberOfParticipants):
    participant = {}
    participant['participantName'] = 'participant' + str(participantIx)
    participant['attributes'] = []

    sleep = {}
    productivity = {}

    sleep['attributeName'] = 'sleep'
    sleep['attributeData'] = []
    productivity['attributeName'] = 'productivity'
    productivity['attributeData'] = []

    currentDate = startDate
        
    while currentDate <= endDate:
##        print (currentDate.strftime(dateFormat))

        sleepPair = {}
        productivityPair = {}
        
        sleepPair['date'] = currentDate.strftime(dateFormat)
        productivityPair['date'] = currentDate.strftime(dateFormat)

        sleepPair['value'] = max(random.uniform(2,3), abs(trendSleep[participantIx] + random.uniform(-deviationSleep[participantIx], deviationSleep[participantIx]))) * 60
        productivityPair['value'] = max(random.uniform(0,1), abs((trendProd[participantIx] + random.uniform(-deviationSleep[participantIx], deviationProd[participantIx])) * 60))

        sleep['attributeData'].append(sleepPair)
        productivity['attributeData'].append(productivityPair)

        trendSleep[participantIx] += trendDeltaSleep[participantIx]
        trendProd[participantIx] += trendDeltaProd[participantIx]

        trendDeltaSleep[participantIx] += trendDelta2Sleep[participantIx]
        trendDeltaProd[participantIx] += trendDelta2Prod[participantIx]

        currentDate += delta
    
    participant['attributes'].append(productivity)
    participant['attributes'].append(sleep)
        
    data['participants'].append(participant)

with open('data.json', 'w') as outfile:
    json_data = json.dump(data, outfile)
